AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
