default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] || "hot_validation" %>
  username: <%= ENV['DATABASE_USER'] || "hot_validation" %>
  password: <%= ENV['DATABASE_PASSWORD'] || "hot_validation" %>
  port: <%= ENV['DATABASE_PORT'] || "5432" %>
  host: <%= ENV['DATABASE_HOST'] || "127.0.0.1" %>

development:
  <<: *default
  port: 5436

test:
  <<: *default
  database: hot_validation_test
  port: 5436

production:
  <<: *default
  database: hot_validation_production
  username: hot_validation
  password: <%= ENV['HOT_VALIDATION_DATABASE_PASSWORD'] %>
